import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import fg from "fast-glob";
import type { Repo } from "./ingest.js";
import type { Finding } from "./report.js";

// AI PROVENANCE FINGERPRINTING — the differentiator no generic scanner can claim.
//
// Different AI builders leave different structural signatures (dedicated config
// dirs, marker deps, scaffolded folder shapes, boilerplate comments). Detect WHO
// built the repo, then apply that tool's KNOWN failure modes as targeted priors —
// "this is a Lovable app, so RLS is your only access control and it's usually off;
// here's where to look." A clone can copy the regexes; it can't copy the corpus of
// "how each tool specifically fails" that makes these priors worth raising.
//
// Fully deterministic (no Claude, no network — the moat). The fingerprint itself is
// informational; the failure-mode priors are ADVISORY (they prime the review, they
// never gate a merge) and are clearly labelled as builder patterns to verify, not
// confirmed bugs in this repo.

export type Builder =
  | "lovable"
  | "bolt"
  | "v0"
  | "replit"
  | "cursor"
  | "claude-code"
  | "copilot"
  | "windsurf"
  | "unknown";

// App GENERATORS build the whole app from a prompt — their shipped code has
// characteristic failure modes. ASSISTANTS help a human edit — their marker just
// means "AI-assisted", a weaker (drift) prior.
type BuilderClass = "generator" | "assistant";

export interface BuilderMatch {
  builder: Builder;
  name: string; // display name
  klass: BuilderClass;
  confidence: number; // 0..1
  signals: string[]; // human-readable evidence
}

export interface ProvenanceResult {
  top: BuilderMatch | null; // highest-confidence builder above threshold
  candidates: BuilderMatch[]; // all detected, confidence-sorted
  findings: Finding[]; // failure-mode priors for the top builder
}

const DETECT_THRESHOLD = 0.35;

// ── file helpers (config/markers live outside repo.files, which is source-only) ──
function readRoot(root: string, rel: string): string | null {
  try {
    return readFileSync(path.join(root, rel), "utf8");
  } catch {
    return null;
  }
}
function existsAny(root: string, rels: string[]): boolean {
  return rels.some((r) => existsSync(path.join(root, r)));
}
function globRoot(root: string, patterns: string[]): string[] {
  return fg.sync(patterns, { cwd: root, dot: true, ignore: ["**/node_modules/**"] });
}
function pkgText(root: string): string {
  return readRoot(root, "package.json") ?? "";
}
// NOTE: we deliberately DON'T fingerprint by scanning source *content* for tool-name
// strings (e.g. "Generated by v0"). It's unreliable and a footgun — any repo that
// merely discusses these builders (Shepherd's own source, a blog, docs) would match.
// Every signal below is a config file, a marker dir, a dependency, or a folder shape:
// things a user's actual generated app has, and that prose about the tool does not.

interface Signal {
  weight: number;
  note: string;
}
function score(signals: Signal[]): { confidence: number; evidence: string[] } {
  const total = signals.reduce((s, x) => s + x.weight, 0);
  return { confidence: Math.min(0.99, total), evidence: signals.map((s) => s.note) };
}

// ── per-builder signature detectors ─────────────────────────────────────────────
function detectLovable(repo: Repo): Signal[] {
  const root = repo.root;
  const pkg = pkgText(root);
  const s: Signal[] = [];
  if (/"lovable-tagger"/.test(pkg)) s.push({ weight: 0.8, note: "`lovable-tagger` dev dependency" });
  const vite = readRoot(root, "vite.config.ts") ?? readRoot(root, "vite.config.js") ?? "";
  if (/componentTagger|lovable-tagger/.test(vite)) s.push({ weight: 0.6, note: "`componentTagger()` wired into vite.config" });
  const readme = (readRoot(root, "README.md") ?? "") + (readRoot(root, "README") ?? "");
  if (/lovable\.dev|built with lovable|lovable project/i.test(readme)) s.push({ weight: 0.6, note: "README references lovable.dev" });
  if (existsSync(path.join(root, "src", "integrations", "supabase"))) s.push({ weight: 0.3, note: "`src/integrations/supabase/` scaffold (Lovable layout)" });
  if (existsSync(path.join(root, "components.json")) && /vite/.test(pkg) && /react/.test(pkg)) s.push({ weight: 0.1, note: "shadcn `components.json` on a Vite + React app" });
  return s;
}
function detectBolt(repo: Repo): Signal[] {
  const root = repo.root;
  const s: Signal[] = [];
  if (existsSync(path.join(root, ".bolt"))) s.push({ weight: 0.85, note: "`.bolt/` directory" });
  if (existsAny(root, [".bolt/config.json", ".bolt/prompt", ".bolt/ignore"])) s.push({ weight: 0.1, note: "`.bolt/` config files" });
  return s;
}
function detectV0(repo: Repo): Signal[] {
  const root = repo.root;
  const pkg = pkgText(root);
  const s: Signal[] = [];
  const readme = readRoot(root, "README.md") ?? "";
  // v0 exports keep a "Built with v0" / v0.dev line in the README — a strong, robust
  // signal (vs. scanning code, which v0 doesn't reliably stamp).
  if (/v0\.dev|built with v0/i.test(readme)) s.push({ weight: 0.7, note: "README references v0.dev" });
  if (existsSync(path.join(root, "components.json")) && /"next"\s*:/.test(pkg) && existsSync(path.join(root, "components", "ui"))) {
    s.push({ weight: 0.2, note: "Next.js + shadcn `components/ui/` (v0 default stack)" });
  }
  return s;
}
function detectReplit(repo: Repo): Signal[] {
  const root = repo.root;
  const s: Signal[] = [];
  if (existsSync(path.join(root, ".replit"))) s.push({ weight: 0.8, note: "`.replit` config" });
  if (existsSync(path.join(root, "replit.nix"))) s.push({ weight: 0.3, note: "`replit.nix`" });
  return s;
}
function detectCursor(repo: Repo): Signal[] {
  const root = repo.root;
  const s: Signal[] = [];
  if (existsAny(root, [".cursorrules"])) s.push({ weight: 0.7, note: "`.cursorrules`" });
  if (existsSync(path.join(root, ".cursor")) || globRoot(root, [".cursor/rules/**/*.mdc"]).length > 0) s.push({ weight: 0.6, note: "`.cursor/` rules directory" });
  return s;
}
function detectClaudeCode(repo: Repo): Signal[] {
  const root = repo.root;
  const s: Signal[] = [];
  if (existsSync(path.join(root, "CLAUDE.md"))) s.push({ weight: 0.7, note: "`CLAUDE.md`" });
  if (existsSync(path.join(root, ".claude"))) s.push({ weight: 0.5, note: "`.claude/` directory" });
  if (existsSync(path.join(root, ".mcp.json"))) s.push({ weight: 0.2, note: "`.mcp.json`" });
  return s;
}
function detectCopilot(repo: Repo): Signal[] {
  const root = repo.root;
  const s: Signal[] = [];
  if (existsSync(path.join(root, ".github", "copilot-instructions.md"))) s.push({ weight: 0.8, note: "`.github/copilot-instructions.md`" });
  return s;
}
function detectWindsurf(repo: Repo): Signal[] {
  const root = repo.root;
  const s: Signal[] = [];
  if (existsAny(root, [".windsurfrules"])) s.push({ weight: 0.7, note: "`.windsurfrules`" });
  if (existsSync(path.join(root, ".windsurf"))) s.push({ weight: 0.5, note: "`.windsurf/` directory" });
  return s;
}

const REGISTRY: Array<{ builder: Builder; name: string; klass: BuilderClass; detect: (r: Repo) => Signal[] }> = [
  { builder: "lovable", name: "Lovable", klass: "generator", detect: detectLovable },
  { builder: "bolt", name: "Bolt.new", klass: "generator", detect: detectBolt },
  { builder: "v0", name: "v0 (Vercel)", klass: "generator", detect: detectV0 },
  { builder: "replit", name: "Replit", klass: "generator", detect: detectReplit },
  { builder: "cursor", name: "Cursor", klass: "assistant", detect: detectCursor },
  { builder: "claude-code", name: "Claude Code", klass: "assistant", detect: detectClaudeCode },
  { builder: "copilot", name: "GitHub Copilot", klass: "assistant", detect: detectCopilot },
  { builder: "windsurf", name: "Windsurf", klass: "assistant", detect: detectWindsurf },
];

// ── known failure modes per generator (the corpus that makes this defensible) ────
// Each is an ADVISORY prior — a "this builder commonly does X; verify Y here" — not
// a confirmed bug. Phrased so the user knows it's a pattern to check.
type Prior = Omit<Finding, "disposition">;

function lovablePriors(repo: Repo): Prior[] {
  const where = existsSync(path.join(repo.root, "src", "integrations", "supabase")) ? "src/integrations/supabase" : "your Supabase tables";
  return [
    {
      id: "prov-lovable-rls",
      severity: "warn",
      file: where,
      message:
        "Lovable apps talk to Supabase from the browser with the publishable anon key — that's by design, which means Row-Level Security IS your access control. Lovable frequently ships with RLS disabled or wide-open policies. Verify every table has RLS enabled with non-trivial, per-user policies.",
    },
    {
      id: "prov-lovable-clientauth",
      severity: "warn",
      file: where,
      message:
        "Authorization in Lovable apps is usually enforced only in React (route guards, conditional rendering). The Supabase client is directly reachable, so anyone can query past the UI. Enforce access in RLS policies / edge functions, never in components alone.",
    },
    {
      id: "prov-lovable-edge-ratelimit",
      severity: "warn",
      file: "supabase/functions",
      message:
        "Supabase Edge Functions scaffolded by Lovable typically have no auth and no rate limit on expensive/AI/email calls — a textbook cost-bomb. Add auth + a rate limiter in front of any cost-incurring function.",
    },
    {
      id: "prov-lovable-validation",
      severity: "info",
      file: where,
      message: "Lovable-generated forms usually trust client input. Add server-side validation (zod, DB constraints/checks) rather than relying on the UI.",
    },
  ];
}
function boltPriors(_repo: Repo): Prior[] {
  return [
    {
      id: "prov-bolt-noserver",
      severity: "warn",
      file: "src",
      message:
        "Bolt apps run in a browser WebContainer and are often client-only — state lives in the browser with no real backend or durable persistence. Confirm there's a server of record before treating any data as saved.",
    },
    {
      id: "prov-bolt-keys",
      severity: "warn",
      file: "src",
      message: "Bolt frequently hardcodes API keys in client code or ships them via browser-exposed env. Move every secret server-side; anything in the bundle is public.",
    },
    {
      id: "prov-bolt-validation",
      severity: "info",
      file: "src",
      message: "Validation in Bolt apps is usually client-only. Add server-side checks before any write reaches a real datastore.",
    },
  ];
}
function v0Priors(_repo: Repo): Prior[] {
  return [
    {
      id: "prov-v0-action-auth",
      severity: "warn",
      file: "app",
      message:
        "v0 generates Server Actions / route handlers that often skip auth and authorization. Verify every mutating action checks the session AND the caller's permission to act on that resource.",
    },
    {
      id: "prov-v0-public-env",
      severity: "warn",
      file: "next.config",
      message: "Check `NEXT_PUBLIC_`-prefixed env vars — anything with that prefix is inlined into the client bundle. Secrets must not use it.",
    },
    {
      id: "prov-v0-mockdata",
      severity: "info",
      file: "app",
      message: "v0 commonly leaves mock/placeholder data and TODOs in place of real fetching. Confirm data is wired to real sources before shipping.",
    },
  ];
}
function replitPriors(_repo: Repo): Prior[] {
  return [
    {
      id: "prov-replit-secrets",
      severity: "warn",
      file: ".replit",
      message: "Replit projects often commit secrets into `.replit`/env or rely on the Replit Secrets pane that doesn't carry over when exported. Audit for committed keys and move them to a real secret store.",
    },
  ];
}
function assistantPrior(name: string): Prior[] {
  return [
    {
      id: "prov-ai-assisted",
      severity: "info",
      file: ".",
      message: `This repo carries ${name} AI-assist markers. AI-assisted code tends to drift — inconsistent patterns across files, partial refactors, and duplicated logic where the model didn't see the whole picture. Watch for architectural drift and copy-pasted blocks during review.`,
    },
  ];
}

function priorsFor(m: BuilderMatch, repo: Repo): Prior[] {
  switch (m.builder) {
    case "lovable":
      return lovablePriors(repo);
    case "bolt":
      return boltPriors(repo);
    case "v0":
      return v0Priors(repo);
    case "replit":
      return replitPriors(repo);
    default:
      return assistantPrior(m.name);
  }
}

// ── public API ──────────────────────────────────────────────────────────────────
export function detectProvenance(repo: Repo): ProvenanceResult {
  const candidates: BuilderMatch[] = [];
  for (const r of REGISTRY) {
    const signals = r.detect(repo);
    if (signals.length === 0) continue;
    const { confidence, evidence } = score(signals);
    if (confidence < DETECT_THRESHOLD) continue;
    candidates.push({ builder: r.builder, name: r.name, klass: r.klass, confidence, signals: evidence });
  }

  // Generators win the "top" slot over assistants (their failure modes are the
  // valuable priors); within a class, highest confidence wins.
  candidates.sort((a, b) => {
    if (a.klass !== b.klass) return a.klass === "generator" ? -1 : 1;
    return b.confidence - a.confidence;
  });

  const top = candidates[0] ?? null;
  const findings: Finding[] = top ? priorsFor(top, repo).map((p) => ({ ...p, disposition: "advise" })) : [];
  return { top, candidates, findings };
}

// The advisory findings, for folding into the deterministic scan / audit / git-check.
export function provenanceFindings(repo: Repo): Finding[] {
  return detectProvenance(repo).findings;
}

// A pretty terminal card for the fingerprint — used by `/fingerprint` and boot.
export function buildFingerprintCard(r: ProvenanceResult): string {
  if (!r.top) {
    return [
      "🔎 Provenance: no AI-builder fingerprint detected.",
      "   No Lovable / Bolt / v0 / Replit / Cursor / Claude / Copilot / Windsurf markers found —",
      "   this looks hand-built or the markers were stripped. Reviewing on general priors.",
    ].join("\n");
  }
  const pct = (c: number) => `${Math.round(c * 100)}%`;
  const lines: string[] = [];
  lines.push(`🔎 Built by: ${r.top.name} (${pct(r.top.confidence)} confidence)`);
  for (const s of r.top.signals) lines.push(`   • ${s}`);
  if (r.top.klass === "generator" && r.findings.length) {
    lines.push("");
    lines.push(`   Known failure modes for ${r.top.name} — verify these here:`);
    for (const f of r.findings) {
      const mark = f.severity === "warn" ? "⚠" : "·";
      lines.push(`     ${mark} [${f.id}] ${f.message.split(" — ")[0].split(". ")[0]}.`);
    }
  }
  const others = r.candidates.slice(1).filter((c) => c.confidence >= DETECT_THRESHOLD);
  if (others.length) {
    lines.push("");
    lines.push(`   Also detected: ${others.map((o) => `${o.name} (${pct(o.confidence)})`).join(", ")}`);
  }
  return lines.join("\n");
}
